module.exports = {
  MAILGUN_USER: 'ENTER YOUR MAILJET USERNAME',
  MAILGUN_PASS: 'ENTER YOUR MAILJET PASSWORD',
  SENDER_EMAIL: 'ENTER YOUR VERIFIED MAILJET EMAIL ID',
  SMS_ID: 'ENTER YOUR DATAGENIT AUTHORIZATION KEY'
};


